version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: yoga_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yoga_db
      MYSQL_USER: yoga_user
      MYSQL_PASSWORD: yoga_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yoga_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yoga_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=yoga_user
      - DB_PASSWORD=yoga_password
      - DB_NAME=yoga_db
      - PORT=3000
    volumes:
      - ./src:/app/src
    command: sh -c "npm install && npm run dev"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: